embedding:
  api_base: http://localhost:3001/v1/embeddings

chroma:
  host: localhost
  port: 3400
  collection: caracal-base

sources:
  # Add local knowledge source
  - name: example_knowledge_funny_jokes
    type: local
    path: /path/to/local/example_knowledge_funny_jokes

  # Or fetch an entire docs directory recursively (github_md_doc_dir)
  - name: fiteo-docs
    type: github_md_doc_dir
    repo: mariuszmarzec/fiteo
    path: docs
    branch: master
