embedding:
  api_base: http://localhost:3001/v1/embeddings

chroma:
  host: localhost
  port: 3400
  collection: caracal-base

sources:
  # Add local knowledge source
  - name: example_knowledge_funny_jokes
    type: local
    path: ./example_knowledge_funny_jokes
